apiVersion: v1
kind: Pod
metadata:
  name: static-web
  namespace: app
spec:
  containers:
    - name: web
      image: akhil92/staticweb:1.0
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
