apiVersion: v1
kind: Pod
metadata:
  name: static-web
spec:
  containers:
    - name: web
      image: akhil92/staticweb
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
