---
apiVersion: v1
kind: Pod
metadata:
  name: static-web
  namespace: app
  labels:
    app: static-web
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: static-web-service
  namespace: app
spec:
  type: NodePort
  selector:
    app: static-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
